sonar.projectKey=tinyspice123_riftbound_collection_tracker
sonar.organization=tinyspice123
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
sonar.sources=public,scripts
sonar.tests=tests
sonar.exclusions=public/img/**,public/assets/**,**/__pycache__/**
sonar.coverage.exclusions=public/sets.js,public/index.js,public/tracker.js,public/pwa.js
